### ISSUE TITLE
Images in pdf

### ISSUE THREAD

**Issue by anthonyringoet** [alanshaw/grunt-markdown-pdf#2]
Is it possible to have images in the rendered pdf?
There's an issue that the image paths are incorrect because i cannot know where the temporary html files are saved.

In the resulting pdf there are not visible as a result.

**Comment by diamondarts** [comment]
Hello,

notes:
- Option 2 worked for me
- Option 3: I had to replace Alan's code with

        return through2map({wantStrings: true}, function (content) {
            return content.replace(/{{assets}}/g, __dirname);
        });

    using the through2-map plugin.
